name: Matter Linux examples build

on: push

jobs:
  build_prepare:
    name: Prepare build
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
      channel: ${{ steps.version.outputs.channel }}
    steps:
      - name: Checkout build repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Get version
        id: version
        shell: bash
        run: |
          version=$(echo "${{ github.ref }}" | awk -F"/" '{print $NF}')
          if [[ ! -z "${{ github.event.inputs.version }}" ]]; then
            version="${{ github.event.inputs.version }}"
          elif [[ "${version}" =~ (main|dev) ]]; then
            today="$(date --utc '+%Y-%m-%d')"
            midnight_timestamp="$(date --utc +%s --date=$today)"
            calver_date="$(date --utc --date=$today '+%Y.%-m.dev%-d')"
            commit_count="$(git rev-list --count --since=$midnight_timestamp HEAD)"
            commit_count="$(printf "%02d" ${commit_count})"
            version="${calver_date}${commit_count}"
          elif [[ "${{ github.ref }}" =~ ^refs/heads/ ]]; then
            today="$(date --utc '+%Y-%m-%d')"
            midnight_timestamp="$(date --utc +%s --date=$today)"
            calver_date="$(date --utc --date=$today '+%Y.%-m.dev%-d')"
            # Remove invalid chars
            localversion="${version}"
            localversion="${localversion//-/}"
            localversion="${localversion//_/}"
            version="${calver_date}+${localversion}"
          fi
          echo "Building version $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Checkout submodules
        working-directory: ./connectedhomeip/
        run: scripts/checkout_submodules.py --shallow --platform linux
      - name: Apply patches
        working-directory: ./connectedhomeip/
        run: |
          for patch in ../*.patch
          do
              echo "Applying ${patch}"
              patch -p1 < $patch
          done
      - name: Bootstrap
        working-directory: ./connectedhomeip/
        run: bash scripts/bootstrap.sh -p all,linux
      - name: ZAP Code pre-generation
        working-directory: ./connectedhomeip/
        run: scripts/run_in_build_env.sh "scripts/codepregen.py ./zzz_pregenerated/"
      - name: Create Matter SDK tar
        run: |
          tar -caf ../connectedhomeip.tar.zst --exclude ./connectedhomeip/.environment --use-compress-program=zstdmt .
          mv ../connectedhomeip.tar.zst ./connectedhomeip.tar.zst
      - name: Store Matter SDK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: matter-sdk-${{ github.run_id }}
          path: ./connectedhomeip.tar.zst

  build_linux_python_lib:
    name: Build Python wheels for Linux (${{ matrix.arch.name }})
    needs: build_prepare

    strategy:
      matrix:
        arch:
          - name: x86_64
            container: ghcr.io/project-chip/chip-build:22
            runner: ubuntu-22.04
          - name: aarch64
            container: docker.io/agners/aarch64-chip-build:22
            runner: ARM64

    runs-on: ${{ matrix.arch.runner }}
    permissions:
      contents: write # for actions/upload-release-asset to upload release asset

    defaults:
      run:
        working-directory: ./connectedhomeip/

    container:
      image: ${{ matrix.arch.container }}
      volumes:
        - "/tmp/log_output:/tmp/test_logs"
      options: --sysctl "net.ipv6.conf.all.disable_ipv6=0
        net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1"

    steps:
      - name: Restore Matter SDK from artifacts
        uses: actions/download-artifact@v4
        with:
          name: matter-sdk-${{ github.run_id }}
      - name: Extract Matter SDK from tar
        working-directory: ./
        run: |
          apt update && apt install zstd
          rm -rf connectedhomeip/
          tar -xaf ./connectedhomeip.tar.zst --use-compress-program=zstdmt .
          git config --global --add safe.directory "*"
      - name: Bootstrap
        run: bash scripts/bootstrap.sh -p all,linux
      - name: Setup Build, Run Build and Run Tests
        run: |
          for example in \
                chip-tool \
                chip-cert \
                air-purifier \
                bridge \
                dishwasher \
                light \
                lock \
                refrigerator \
                rvc \
                thermostat ; do
                    scripts/build/build_examples.py \
                        --target "${EXAMPLE_PREFIX}${example}${EXAMPLE_POSTFIX}" \
                        --pregen-dir ./zzz_pregenerated \
                        --pw-command-launcher=ccache \
                        build
                    find out/ -type f -executable -exec cp {} bin/ \;
                    rm -r out/
                done
      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chip-wheels-linux-${{ matrix.arch.name }}
          path: ./connectedhomeip/bin/
      - name: Upload wheels as release assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./connectedhomeip/bin/

